### ISSUE TITLE
Change the url to request to populate a zip file

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/generator#11]
The current service to populate a Spring Boot zip file is defined as such `/template/${id}` where the id could be one the template proposed : crud, rest, simple

As the template is optional and non required at all when we will populate a project for a request containing dependencies = starters, then we should revisit the URL and certainly remove this path

- Now

  curl https://start.snowdrop.me/template/crud -d web -d websocket

Result : project created using `simple` template with the pom file including the GAVs associated with the modules `web`, `websocket`

- Proposition

  curl https://start.snowdrop.me -d web -d websocket

**Comment by geoand** [comment]
How about https://start.snowdrop.me/app ?

**Comment by cmoulliard** [comment]
Why do propose to append `/app` ? What is the idea/motivation behind that ?

**Comment by geoand** [comment]
I don't like the fact that the application would answer on the default path
by creating a zip file.
And in moving away from template (since as you very eloquently pointed out
is not the only mode now), app seems like the most generic noun to use.

**Comment by cmoulliard** [comment]
I like the idea too. I will use `/app` as endpoint/path ;-)

**Comment by geoand** [comment]
Sounds good 😉!
