### ISSUE TITLE
Refactor ConfigMap properties to match CLI parameter names

### ISSUE THREAD

**Issue by lincolnthree** [snowdrop/generator#14]
- [x] bom -> bomVersion

The above is probably the most important change, however I could also see an argument for changing the "starters" property in the "module" configuration to be "dependencies" instead. Or changing the "dependencies" CLI parameter to "module". I would recommend the following, but would like to hear what the team thinks about this - from a 3rd party dev's/user's perspective:

- [x] Change "dependencies" parameter in CLI to "modules" (see `sb help create`)
- [x] Change "module.starters" config property to  "module.dependencies", as they could also contain non-starter/non-spring deps at some point for other integrations w/Red Hat tech (https://github.com/snowdrop/generator/blob/master/conf/generator.yaml)

@gytis @metacosm @geoand @iocanel @cmoulliard ?

**Comment by cmoulliard** [comment]
I was using `dependencies` as this is the parameter used by `start.spring.io`. Personally, your approach is more logic and I agree on the proposition. 

From the client point of view, they will use the following command to specify the module to be used

```
sb create -m web -m websocket -m security ....
```

Question : Should we use the singular or plural form ? @lincolnthree 

```
sb create --module web ... OR sb create --modules web 
```

**Comment by lincolnthree** [comment]
I think the singular form makes the most sense for CLI.
