### ISSUE TITLE
Change name of "simple" template

### ISSUE THREAD

**Issue by geoand** [snowdrop/generator#21]
I think the name "simple" for the template is missleading, since we are using it in order to populate a custom pom based on what modules the user selects.

I propose we rename it to `custom`.

WDYT @cmoulliard @lincolnthree ?

**Comment by cmoulliard** [comment]
I had the same feeling this morning in my bed when I was thinking about this `simple` word ;-). I agree with you that it must be changed

Some propositions : 

- [ ] `custom`
- [ ]  `basic`
- [ ]  `spring-boot-app`

@geoand @iocanel @metacosm @lincolnthree

**Comment by geoand** [comment]
My vote is for `custom` :)

**Comment by lincolnthree** [comment]
Actually I agree with that. I like "custom" as well.

**Comment by lincolnthree** [comment]
Dang github!

**Comment by cmoulliard** [comment]
Don't close as some code's changes are needed ;-)

- Rename the `simple` tmpl folder to `custom`
- Update the `generator.yaml` file to use custom instead of `simple`
- Review code's logic and adapt it as there is a if/ten/else condition checking if template is equal to `simple`

**Comment by geoand** [comment]
Sounds good to me, I can start work on this tomorrow and issue a PR that you can review when I'm done.

**Comment by lincolnthree** [comment]
I'll prepare a PR for snowdrop.me that can be merged once this change is made.

**Comment by geoand** [comment]
Cool, I'll most likely ping you tomorrow then :)

**Comment by cmoulliard** [comment]
ok for `custom` too
