### ISSUE TITLE
Automatically add changes between versions to github releases

### ISSUE THREAD

**Issue by geoand** [snowdrop/generator#25]

**Comment by cmoulliard** [comment]
We could but if a new feature has been added then it will be required to open the link `compare` in order to see all the commits and try to figure out which commit corresponds to a new feature ....

**Comment by geoand** [comment]
OK then, I guess we need to automate what we are currently doing manually :)

**Comment by cmoulliard** [comment]
How could you then automate the process to add a section (e.g. ### Features) and next the `commit's link` - `text`

**Comment by geoand** [comment]
Can you give me an example? I don't see what anywhere

**Comment by cmoulliard** [comment]
Example

- This section could be automated as you suggested
```
### Change log 
fdc1a52 (tag: release-0.0.13) Add debug messages
c3648f0, 24e6d52 Update README.md
```
- New features section is done manually as we extract such info from the change log
```
### New Features (is done manually as we extract such info from the change log) 
283f85f Add function to find the corresponding Snowdrop BOM when no defined. Move internal functions
76d9452 Add module for spring cloud kubernetes
```

**Comment by geoand** [comment]
Yes, I don't think we can automate the second part. Do we really need it?

**Comment by cmoulliard** [comment]
No as this is the responsability of the release's owner to enhance the content of the release note
